In [1]:
import numpy as np
from scipy.spatial import distance

In [7]:
from pkg_resources import get_distribution
import platform
print("python", platform.python_version())
print("")
libs = ["numpy", "scipy"]
for lib in libs:
    version = get_distribution(lib).version
    print(lib, version)

python 3.5.2

numpy 1.13.1
scipy 0.19.1


In [12]:
docs = [
    ["データ", "分析", "エンジニア"],
    ["データ", "アナリスト"],
    ["ソフトウェア", "エンジニア"]
]

In [13]:
words = {}
for doc in docs:
    for word in doc:
        if word not in words:
            words[word] = len(words)
print(words)

{'ソフトウェア': 4, 'データ': 0, '分析': 1, 'エンジニア': 2, 'アナリスト': 3}


In [16]:
docs_p = []
for doc in docs:
    doc_p = []
    for i in range(len(doc)):
        for j in range(i, len(doc)):
            doc_p.append((doc[i], doc[j])) # 共起ペアを作成
    docs_p.append(doc_p)
print(docs_p)

[[('データ', 'データ'), ('データ', '分析'), ('データ', 'エンジニア'), ('分析', '分析'), ('分析', 'エンジニア'), ('エンジニア', 'エンジニア')], [('データ', 'データ'), ('データ', 'アナリスト'), ('アナリスト', 'アナリスト')], [('ソフトウェア', 'ソフトウェア'), ('ソフトウェア', 'エンジニア'), ('エンジニア', 'エンジニア')]]


In [19]:
cnts = np.zeros((len(words), len(words)))
for doc_p in docs_p:
    for p in doc_p:
        cnts[words[p[0]], words[p[1]]] += 1
        cnts[words[p[1]], words[p[0]]] += 1
for i in range(len(words)):
    cnts[i, i] /= 2
print(cnts)

[[ 2.  1.  1.  1.  0.]
 [ 1.  1.  1.  0.  0.]
 [ 1.  1.  2.  0.  1.]
 [ 1.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  1.]]


In [20]:
jaccards = 1-distance.cdist(cnts, cnts, "jaccard") # Jaccard係数行列（共起パターンの類似度）
print(jaccards)

[[ 1.    0.5   0.2   0.25  0.2 ]
 [ 0.5   1.    0.5   0.25  0.25]
 [ 0.2   0.5   1.    0.2   0.25]
 [ 0.25  0.25  0.2   1.    0.  ]
 [ 0.2   0.25  0.25  0.    1.  ]]
