In [1]:
import numpy as np
import pandas as pd
from IPython.display import display
import matplotlib
import matplotlib.pylab as plt
matplotlib.style.use("ggplot")
from sklearn import datasets
from sklearn import svm
from sklearn.metrics import confusion_matrix, accuracy_score

In [2]:
from pkg_resources import get_distribution
import platform
print("python", platform.python_version())
print("")
libs = ["pandas", "numpy", "matplotlib", "scikit-learn"]
for lib in libs:
    version = get_distribution(lib).version
    print(lib, version)

python 3.5.2

pandas 0.20.3
numpy 1.13.1
matplotlib 2.0.2
scikit-learn 0.18.2


In [3]:
# irisデータセット
iris = datasets.load_iris()
data = pd.DataFrame(data= np.c_[iris["data"], iris["target"]], columns= iris["feature_names"] + ["target"])
print(len(data))
display(data.head())

150


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [5]:
# SVMで予測精度を確認してみる

t = data["target"]
x_label = iris["feature_names"] # ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
x = data[x_label]
model = svm.SVC()
model.fit(x, t) # モデルフィッティング
print("混合行列: ")
y = model.predict(x)
print(confusion_matrix(y, t)) # 混合行列
print("教師データ正解率: ", accuracy_score(y, t)) # 正解率

混合行列: 
[[50  0  0]
 [ 0 48  0]
 [ 0  2 50]]
教師データ正解率:  0.986666666667
